apiVersion: v1
data:
  # terra node config
  MONIKER: UnionMarket
  CHAIN_ID: columbus-3
  BOOTSTRAP: "FALSE"
  TERRAD_HOME: /.terrad
  GENESIS_URL: https://columbus-genesis.s3-ap-northeast-1.amazonaws.com/genesis.json
  SEEDS: 447ba60df6fdc2466e1ab4c328e100d6bc5765f8@seed-only.terra-columbus-3.bas.network:26656,6be0856f6365559fdc2e9e97a07d609f754632b0@terra-columbus-3-seed.nodes.polychainlabs.com:26656,b416f0b04e2c71b8d76f993468352030e2dcf2a9@public-seed-node.columbus.certus.one:26656,87048bf71526fb92d73733ba3ddb79b7a83ca11e@public-seed.terra.dev:26656,b5205baf1d52b6f91afb0da7d7b33dcebc71755f@public-seed2.terra.dev:26656,535222fdb795df6653934f22b8e5f16fdfacc9f6@seed.terra.de-light.io:26656,bae08cc880c20aeda68a5a890a71a9b44ac73cb4@terra-seed-eu.chorus.one:28657,925ecc3de9e2ac65a203beb2333ced1a00c135ed@terra-seed-us.chorus.one:28657
  PERSISTENT_PEERS: e6325ba7c490ba371135c9f3fcead66da1bd8cf1@terra-sentry01.dokia.cloud:26656,dba5defd7b120937da37aea7f37d06870637558d@terra-sentry02.dokia.cloud:26656,eb4ce12133c450ba6665e06309570ea2843e21d8@167.86.104.33:26656,7277be5ce17d60cf26c92a7cafbb9fc7da7f2be5@51.38.103.128:26656,1cb3e13efe7ca25fb68249169a15e85e53c3b3e9@terra-main.peer.nodeateam.kr:26656,46bc5183ef3b6ea9ffa84df16d6a5aa4a642427a@node.terra.forbole.com:26656
  ADDR_BOOK_STRICT: "false"
  PROMETHEUS_LISTEN_ADDR: "56660"
  MAX_OPEN_CONNECTIONS: "10"
  LCD_PORT: "5317"
  RPC_PORT: "56657"
  P2P_PORT: "56656"
  PROXY_APP_PORT: "56658"
  CORS_ALLOWED_ORIGINS: "*"
  PROMETHEUS: "true"

  # prometheus config
  PROMETHEUS_L_ADDR: "0.0.0.0"
  PROMETHEUS_PORT: "9050"
  JOBNAME: "terra-001"
  TARGET_HOST: "terra-001"
  TARGET_PORT: "56660"
  INSTANCE: "terra-001"

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: terra-config
